{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/discounts": {
      "get": {
        "summary": "Calculate Discount",
        "tags": [
          "Discounts"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "items",
            "in": "query",
            "type": "string",
            "description": "Item List",
            "required": true
          }
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "fetched user info successfully"
          }
        }
      }
    },
    "/item_total": {
      "get": {
        "summary": "List Item Totals",
        "tags": [
          "Products"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "str",
            "in": "query",
            "type": "string",
            "description": "Item Code List",
            "required": true
          }
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "fetched user info successfully"
          }
        }
      }
    },
    "/products": {
      "get": {
        "summary": "List Products",
        "tags": [
          "Products"
        ],
        "consumes": [
          "application/json"
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "fetched user info successfully"
          }
        }
      }
    },
    "/products/{id}": {
      "put": {
        "summary": "Update Product Price",
        "tags": [
          "Product"
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "security": [
          {
            "Bearer": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "type": "integer",
            "description": "product id",
            "required": true
          },
          {
            "name": "price",
            "in": "query",
            "type": "integer",
            "description": "product price",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    }
  }
}